### ISSUE TITLE
8-ball reincarnated ran out of credits

### ISSUE THREAD

**Issue by glitchyfuzzy** [Captainexpo-1/8-ball-reincarnated#6]
![image](https://github.com/Captainexpo-1/8-ball-reincarnated/assets/119808306/5b563868-22ab-4fab-b66f-908ea2c9e26a)

**Comment by ia74** [comment]
that is the shared api key hitting the limit

**Comment by glitchyfuzzy** [comment]
Yeah my bad I noticed it shortly afterward and forgot to close it
